name: loose
homepage: "https://github.com/kirklink/loose"
description: "Library for working with Google Cloud Firestore in a server application."
version: 0.0.80

environment:
  sdk: '>=2.8.0 <3.0.0'
dependencies:
  googleapis_auth: ^1.1.0
dev_dependencies:
  pedantic: ^1.11.0
  