targets:
  $default:
    builders:
      loose_builder:
        enabled: true

builders:
  loose_builder:
    import: "package:loose_builder/loose_builder.dart"
    builder_factories: ["LooseBuilder"]
    build_extensions: {".dart": [".loose.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]