publish_to: none
name: loose_builder
homepage: "https://github.com/kirklink/loose"
description: "Library for working with Google Cloud Firestore. This is the code generator."
version: 0.1.0-nullsafety.0
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  # loose: ^0.0.80
  loose:
    path: ../loose
  source_gen: ^1.0.0
  build: ^2.0.0
  analyzer: ^1.3.0
  recase: ^4.0.0-nullsafety.0
dev_dependencies:
  build_runner: ^1.9.0
  