name: loose_builder
homepage: "https://github.com/kirklink/loose"
description: "Library for working with Google Cloud Firestore. This is the code generator."
version: 0.0.32
environment:
  sdk: '>=2.8.0 <3.0.0'
dependencies:
  loose: ^0.0.32
  # loose:
  #   path: ../loose
  source_gen: ^0.9.0
  build: ^1.3.0
  analyzer: '>=0.35.0 <0.40.0'
  recase: ^3.0.0
dev_dependencies:
  build_runner: ^1.9.0
  